name: Run Staffing Model (Manual Input)

on:
  workflow_dispatch:
    inputs:
      total_rooms:
        description: "Comma-separated total rooms (example: 69,68)"
        required: true
      trainees:
        description: "Comma-separated trainee counts (example: 28,31)"
        required: true
      crnas:
        description: "Comma-separated CRNA counts (example: 28,24)"
        required: true
      faculty:
        description: "Comma-separated faculty counts (example: 36,34)"
        required: true

jobs:
  run-staffing-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run staffing model
        run: |
          python staffing_model.py \
            --total_rooms "${{ github.event.inputs.total_rooms }}" \
            --trainees "${{ github.event.inputs.trainees }}" \
            --crnas "${{ github.event.inputs.crnas }}" \
            --faculty "${{ github.event.inputs.faculty }}"

      - name: Upload Excel output
        uses: actions/upload-artifact@v4
        with:
          name: staffing-model-output
          path: staffing_model_output.xlsx
